[package]
name = "invsearch"
version = "0.1.0"
authors = ["Stefan Junker <mail@stefanjunker.de>"]

[dependencies]
assert_cli = "0.5"
libc = "0.2"
nom = { version = "3.2" } #, features = ["nightly"] }
log = "0.3"
env_logger = "0.4"
futures = "0.1.14"
hyper = "0.11.2"