version: '3'
volumes:
    pgdata:
      external:
        name: invsearch-dev_postgres_data
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: myexample
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
        - "8080:8080"